/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ALLOWED_THEMES: typeof import('./src/composables/useTheme').ALLOWED_THEMES
  const EffectScope: typeof import('vue').EffectScope
  const FieldContextKey: typeof import('vee-validate').FieldContextKey
  const FormContextKey: typeof import('vee-validate').FormContextKey
  const THEME_CHANGE_EVENT: typeof import('./src/composables/useTheme').THEME_CHANGE_EVENT
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const computed: typeof import('vue').computed
  const configure: typeof import('vee-validate').configure
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const db: typeof import('./src/db/fonts').db
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineRule: typeof import('vee-validate').defineRule
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const errorsStore: typeof import('./src/stores/errorsStore').errorsStore
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const initTheme: typeof import('./src/composables/useTheme').initTheme
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const navigationStore: typeof import('./src/stores/appNavigationStore').navigationStore
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const settingsStore: typeof import('./src/stores/settingsNavigationStore').settingsStore
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const siteOptions: typeof import('./src/types/defaultOptions').siteOptions
  const siteStore: typeof import('./src/stores/siteStore').siteStore
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useApi: typeof import('./src/composables/useApi').useApi
  const useAttrs: typeof import('vue').useAttrs
  const useAuthStore: typeof import('./src/stores/authStore').useAuthStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useField: typeof import('vee-validate').useField
  const useFieldArray: typeof import('vee-validate').useFieldArray
  const useFieldError: typeof import('vee-validate').useFieldError
  const useFieldValue: typeof import('vee-validate').useFieldValue
  const useForm: typeof import('vee-validate').useForm
  const useFormErrors: typeof import('vee-validate').useFormErrors
  const useFormValues: typeof import('vee-validate').useFormValues
  const useGoogleFonts: typeof import('./src/composables/useGoogleFonts').default
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useIsFieldDirty: typeof import('vee-validate').useIsFieldDirty
  const useIsFieldTouched: typeof import('vee-validate').useIsFieldTouched
  const useIsFieldValid: typeof import('vee-validate').useIsFieldValid
  const useIsFormDirty: typeof import('vee-validate').useIsFormDirty
  const useIsFormTouched: typeof import('vee-validate').useIsFormTouched
  const useIsFormValid: typeof import('vee-validate').useIsFormValid
  const useIsSubmitting: typeof import('vee-validate').useIsSubmitting
  const useModel: typeof import('vue').useModel
  const useReferenceData: typeof import('./src/composables/useReferenceData').useReferenceData
  const useResetForm: typeof import('vee-validate').useResetForm
  const useSlots: typeof import('vue').useSlots
  const useSubmitCount: typeof import('vee-validate').useSubmitCount
  const useSubmitForm: typeof import('vee-validate').useSubmitForm
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTheme: typeof import('./src/composables/useTheme').useTheme
  const useValidateField: typeof import('vee-validate').useValidateField
  const useValidateForm: typeof import('vee-validate').useValidateForm
  const useValidation: typeof import('./src/composables/useValidation').useValidation
  const validate: typeof import('vee-validate').validate
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { Theme } from './src/composables/useTheme'
  import('./src/composables/useTheme')
  // @ts-ignore
  export type { User, AuthResponse, RegisterRequest, LoginRequest, ApiError, StoredError } from './src/types/auth'
  import('./src/types/auth')
  // @ts-ignore
  export type { PageType, PageSeo, Slug, Page, PageRoute, CreatePageRequest, UpdatePageRequest, ListPagesParams, ListPagesResponse, RoutesResponse } from './src/types/page'
  import('./src/types/page')
  // @ts-ignore
  export type { SiteRoute, Site, CreateSiteRequest, UpdateSiteRequest, PaginatedResponse, ListSitesParams } from './src/types/site'
  import('./src/types/site')
  // @ts-ignore
  export type { ColumnAlign, ColumnSchema, FilterSchema, TableSchema, FilterSchemas } from './src/types/table'
  import('./src/types/table')
  // @ts-ignore
  export type { GoogleFont, ActiveVariant } from './src/db/fonts'
  import('./src/db/fonts')
}
