/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSettings: typeof import('./src/views/AppSettings.vue')['default']
    Background: typeof import('./src/components/editor/settings/fields/Background.vue')['default']
    BlockControls: typeof import('./src/components/editor/blocks/BlockControls.vue')['default']
    BlockSettings: typeof import('./src/components/editor/settings/BlockSettings.vue')['default']
    ColorPicker: typeof import('./src/components/editor/settings/fields/ColorPicker.vue')['default']
    DashBoard: typeof import('./src/views/DashBoard.vue')['default']
    DrawingOverlay: typeof import('./src/components/editor/DrawingOverlay.vue')['default']
    EditorToolbar: typeof import('./src/components/editor/EditorToolbar.vue')['default']
    ErrorsNotifier: typeof import('./src/components/ErrorsNotifier.vue')['default']
    FontFamilyField: typeof import('./src/components/editor/settings/fields/FontFamilyField.vue')['default']
    FontManager: typeof import('./src/components/editor/settings/FontManager.vue')['default']
    Image: typeof import('./src/components/editor/blocks/Image.vue')['default']
    LoginView: typeof import('./src/views/auth/LoginView.vue')['default']
    MainBar: typeof import('./src/components/MainBar.vue')['default']
    MediaManager: typeof import('./src/components/MediaManager.vue')['default']
    ModalNewBlock: typeof import('./src/components/editor/ModalNewBlock.vue')['default']
    NewSection: typeof import('./src/components/editor/NewSection.vue')['default']
    Nothing: typeof import('./src/components/Nothing.vue')['default']
    PageBlock: typeof import('./src/components/editor/PageBlock.vue')['default']
    PageForm: typeof import('./src/components/editor/settings/routing/PageForm.vue')['default']
    PageSection: typeof import('./src/components/editor/PageSection.vue')['default']
    PageSettings: typeof import('./src/components/editor/settings/PageSettings.vue')['default']
    PageTreeNode: typeof import('./src/components/editor/settings/routing/PageTreeNode.vue')['default']
    RangeSlider: typeof import('./src/components/editor/settings/fields/RangeSlider.vue')['default']
    RouterContent: typeof import('./src/components/editor/RouterContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutingSettings: typeof import('./src/components/editor/settings/routing/RoutingSettings.vue')['default']
    SectionRange: typeof import('./src/components/editor/settings/fields/SectionRange.vue')['default']
    SectionSettings: typeof import('./src/components/editor/settings/SectionSettings.vue')['default']
    SettingsPane: typeof import('./src/components/editor/SettingsPane.vue')['default']
    SettingsPanel: typeof import('./src/components/editor/SettingsPanel.vue')['default']
    SiteEditor: typeof import('./src/components/editor/SiteEditor.vue')['default']
    SiteManager: typeof import('./src/components/manager/SiteManager.vue')['default']
    SiteSettings: typeof import('./src/components/editor/settings/SiteSettings.vue')['default']
    Space: typeof import('./src/components/editor/blocks/Space.vue')['default']
    TableModel: typeof import('./src/components/TableModel.vue')['default']
    Text: typeof import('./src/components/editor/blocks/Text.vue')['default']
    TextField: typeof import('./src/components/editor/settings/fields/TextField.vue')['default']
  }
}
